// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
{
    id: 1,
    teachersId: "1234567890",
    name: "John Doe",
    email: "johndoe@gmail.com",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 2,
    teachersId: "1234567890",
    name: "Jane Doe",
    email: "janedoe@gmail.com",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physical", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 3,
    teachersId: "1234567890",
    name: "Anna Santiago",
    email: "annasantiago@gmail.com",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 4,
    teachersId: "1234567890",
    name: "Allen Black",
    email: "allenblack@gmail.com",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 5,
    teachersId: "1234567890",
    name: "Jay French",
    email: "jayfrench@gmail.com",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 6,
    teachersId: "1234567890",
    name: "Mike Geller",
    email: "mikegeller@gmail.com",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 7,
    teachersId: "1234567890",
    name: "Jane Smith",
    email: "janesmith@gmail.com",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 8,
    teachersId: "1234567890",
    name: "Ophella Castro",
    email: "ophellacastro@gmail.com",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 9,
    teachersId: "1234567890",
    name: "Derek Briggs",
    email: "derekbriggs@gmail.com",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 10,
    teachersId: "1234567890",
    name: "John Glover",
    email: "johnglover@gmail.com",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},

];
export const studentsData = [
    {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "johndoe@gmail.com",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
    },
    {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "janedoe@gmail.com",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
    },
    {
    id: 3,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "annasantiago@gmail.com",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 4,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allenblack@gmail.com",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 5,
    studentId: "1234567890",
    name: "Jay French",
    email: "jayfrench@gmail.com",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 6,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mikegeller@gmail.com",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 7,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "janesmith@gmail.com",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 8,
    studentId: "1234567890",
    name: "Ophella Castro",
    email: "ophellacastro@gmail.com",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derekbriggs@gmail.com",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "johnglover@gmail.com",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
];
export const parentData = [
{
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
    {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  
];
export const subjectData = [
    {
        id: 1,
        name: "Physical",
        teachers: ["Alice Phelps", "Russell Davidson"]
    },
    {
    id: 2,
    name: "Cognitive",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "SocioCogitive",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Physical",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Cognitive",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "SocioCogitive",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Physical",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Cognitive",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "SocioCogitive",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Physical",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },

];

export const classesData = [
    {
        id: 1,
        name: "ROOM 1",
        capacity: 20,
        grade: 1,
        supervisor: "Joseph Padilla",
    },
    {
    id: 2,
    name: "ROOM 4",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "ROOM 2",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "ROOM 3",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "ROOM 4",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "ROOM 2",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "ROOM 1",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "ROOM 3",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "ROOM 1",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "ROOM 4",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];
export const lessonsData = [
    {
        id: 1,
        subject: "Cognitive",
        class: "ROOM 1",
        teacher: "Tommy Wise"
    },
    {
        id: 2,
        subject: "Physical",
        class: "ROOM 2",
        teacher: "Rhoda Frank",
    },
    {
        id: 3,
        subject: "Sociocognitive",
        class: "ROOM 3",
        teacher : "Bettie Oliver",
    },
    {
        id: 4,
        subject: "Physical",
        class: "ROOM 2",
        teacher: "Birdie Butler",
    },
    {
        id: 5,
        subject: "Cognitive",
        class: "ROOM 1",
        teacher: "Bruce Rodriguez"
    },
    {
        id: 6,
        subject: "Physical",
        class: "ROOM 2",
        teacher: " Della Dunn",
    },
    {
        id: 7,
        subject: "Socicognitive",
        class: "ROOM 4",
        teacher: "Herman Howard",
    },
    {
        id: 8,
        subject: "Physical",
        class: "ROOM 1",
        teacher: "Julia Pittman",
    },
    {
        id: 9,
        subject: "Soicicognitive",
        class: "ROOM 2",
        teacher: "Martha Morris",
    },
    {
        id: 10,
        subject: "Cognitive",
        class: "ROOM 3",
        teacher: " Ronald Roberts"
    },
];
export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2026-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2026-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2026-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2026-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2026-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2026-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2026-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2026-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2026-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2026-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2026-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2026-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2026-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2026-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2026-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2026-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2026-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2026-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2026-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2026-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2026-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2026-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 7, 12, 8, 0),
    end: new Date(2026, 7, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 7, 12, 9, 0),
    end: new Date(2026, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 7, 12, 10, 0),
    end: new Date(2026, 7, 12, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 7, 12, 11, 0),
    end: new Date(2026, 7, 12, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 7, 12, 13, 0),
    end: new Date(2026, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2026, 7, 12, 14, 0),
    end: new Date(2026, 7, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 7, 13, 9, 0),
    end: new Date(2026, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 7, 13, 10, 0),
    end: new Date(2026, 7, 13, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 7, 13, 11, 0),
    end: new Date(2026, 7, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2026, 7, 13, 14, 0),
    end: new Date(2026, 7, 13, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 7, 14, 8, 0),
    end: new Date(2026, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 7, 14, 10, 0),
    end: new Date(2026, 7, 14, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 7, 14, 13, 0),
    end: new Date(2026, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2026, 7, 14, 14, 0),
    end: new Date(2026, 7, 13, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 7, 15, 9, 0),
    end: new Date(2026, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 7, 15, 10, 0),
    end: new Date(2026, 7, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 7, 15, 11, 0),
    end: new Date(2026, 7, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2026, 7, 15, 14, 0),
    end: new Date(2026, 7, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 7, 16, 8, 0),
    end: new Date(2026, 7, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 7, 16, 9, 0),
    end: new Date(2026, 7, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 7, 16, 11, 0),
    end: new Date(2026, 7, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 7, 16, 13, 0),
    end: new Date(2026, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2026, 7, 16, 14, 0),
    end: new Date(2026, 7, 16, 14, 45),
  },
];