// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
{
    id: 1,
    teachersId: "1234567890",
    name: "John Doe",
    email: "johndoe@gmail.com",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 2,
    teachersId: "1234567890",
    name: "Jane Doe",
    email: "janedoe@gmail.com",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physical", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 3,
    teachersId: "1234567890",
    name: "Anna Santiago",
    email: "annasantiago@gmail.com",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 4,
    teachersId: "1234567890",
    name: "Allen Black",
    email: "allenblack@gmail.com",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 5,
    teachersId: "1234567890",
    name: "Jay French",
    email: "jayfrench@gmail.com",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 6,
    teachersId: "1234567890",
    name: "Mike Geller",
    email: "mikegeller@gmail.com",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 7,
    teachersId: "1234567890",
    name: "Jane Smith",
    email: "janesmith@gmail.com",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 8,
    teachersId: "1234567890",
    name: "Ophella Castro",
    email: "ophellacastro@gmail.com",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 9,
    teachersId: "1234567890",
    name: "Derek Briggs",
    email: "derekbriggs@gmail.com",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 10,
    teachersId: "1234567890",
    name: "John Glover",
    email: "johnglover@gmail.com",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Congnitive", "Sociocognitive"],
    classes: ["ROOM 1", "ROOM 2", "ROOM 3" ],
    address: "123 Main St, Anytown, Nairobi",
},

];
export const studentsData = [
    {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "johndoe@gmail.com",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
    },
    {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "janedoe@gmail.com",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
    },
    {
    id: 3,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "annasantiago@gmail.com",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 4,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allenblack@gmail.com",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 5,
    studentId: "1234567890",
    name: "Jay French",
    email: "jayfrench@gmail.com",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 6,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mikegeller@gmail.com",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 7,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "janesmith@gmail.com",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 8,
    studentId: "1234567890",
    name: "Ophella Castro",
    email: "ophellacastro@gmail.com",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derekbriggs@gmail.com",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
{
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "johnglover@gmail.com",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "ROOM 1",
    address: "123 Main St, Anytown, Nairobi",
},
];
export const parentData = [
{
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
    {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  
];
export const subjectData = [
    {
        id: 1,
        name: "Physical",
        teachers: ["Alice Phelps", "Russell Davidson"]
    },
    {
    id: 2,
    name: "Cognitive",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "SocioCogitive",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Physical",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Cognitive",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "SocioCogitive",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Physical",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Cognitive",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "SocioCogitive",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Physical",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },

];

export const classesData = [
    {
        id: 1,
        name: "ROOM 1",
        capacity: 20,
        grade: 1,
        supervisor: "Joseph Padilla",
    },
    {
    id: 2,
    name: "ROOM 4",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "ROOM 2",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "ROOM 3",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "ROOM 4",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "ROOM 2",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "ROOM 1",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "ROOM 3",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "ROOM 1",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "ROOM 4",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];
export const lessonsData = [
    {
        id: 1,
        subject: "Cognitive",
        class: "ROOM 1",
        teacher: "Tommy Wise"
    },
    {
        id: 2,
        subject: "Physical",
        class: "ROOM 2",
        teacher: "Rhoda Frank",
    },
    {
        id: 3,
        subject: "Sociocognitive",
        class: "ROOM 3",
        teacher : "Bettie Oliver",
    },
    {
        id: 4,
        subject: "Physical",
        class: "ROOM 2",
        teacher: "Birdie Butler",
    },
    {
        id: 5,
        subject: "Cognitive",
        class: "ROOM 1",
        teacher: "Bruce Rodriguez"
    },
    {
        id: 6,
        subject: "Physical",
        class: "ROOM 2",
        teacher: " Della Dunn",
    },
    {
        id: 7,
        subject: "Socicognitive",
        class: "ROOM 4",
        teacher: "Herman Howard",
    },
    {
        id: 8,
        subject: "Physical",
        class: "ROOM 1",
        teacher: "Julia Pittman",
    },
    {
        id: 9,
        subject: "Soicicognitive",
        class: "ROOM 2",
        teacher: "Martha Morris",
    },
    {
        id: 10,
        subject: "Cognitive",
        class: "ROOM 3",
        teacher: " Ronald Roberts"
    },
];